# Generated by Django 4.1.3 on 2022-12-05 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='0712345689', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='phone_number'),
        ),
    ]
